// Generates src/lib/sqlWasmBase64.ts from sql.js's own compiled wasm
// binary. Run via `npm run generate-wasm-asset` whenever the sql.js
// dependency is bumped.
//
// Why this exists: SAM's esbuild BuildMethod has no built-in way to ship
// a real .wasm file alongside bundled Lambda code -- marking sql.js
// "external" (tried first) only tells esbuild not to bundle it, it does
// NOT copy the package into the deployment artifact, so `require('sql.js')`
// would fail at runtime with the module missing entirely (verified by
// inspecting a `sam build` artifact directly -- no node_modules present).
// Embedding the wasm bytes as a base64 string sidesteps the whole
// question: it becomes an ordinary string literal that esbuild bundles
// like any other source, decoded back to bytes at module load via
// sql.js's `wasmBinary` option, no runtime file lookup involved at all.

import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const WASM_PATH = path.join(__dirname, '../node_modules/sql.js/dist/sql-wasm.wasm')
const OUT_PATH = path.join(__dirname, '../src/lib/sqlWasmBase64.ts')

const bytes = readFileSync(WASM_PATH)
const base64 = bytes.toString('base64')

writeFileSync(
  OUT_PATH,
  `// Generated by scripts/generate-wasm-asset.ts from sql.js's compiled
// sql-wasm.wasm -- run \`npm run generate-wasm-asset\` after bumping the
// sql.js dependency. Do not hand-edit.
export const SQL_WASM_BASE64 = ${JSON.stringify(base64)}
`,
)

console.log(
  `Wrote ${OUT_PATH} (${(bytes.length / 1024).toFixed(0)} KB wasm -> ${(base64.length / 1024).toFixed(0)} KB base64)`,
)
