// Proposes a date for every published document. Run from app/:
//
//   node scripts/proposeDates.ts                      # the report
//   node scripts/proposeDates.ts --confidence=low     # just the doubtful ones
//   node scripts/proposeDates.ts --out=dates.sql      # SQL for the confident ones
//   node scripts/proposeDates.ts --out=dates.sql --include-low
//
// Writes nothing to the database, and opens it READ-ONLY. Same shape as
// splitParallelText.ts and importKeepers.ts: the archive is the one
// thing here that cannot be regenerated, so a person reads the change
// before it is applied.
//
// This exists to turn the Archivist's pass from transcription into
// confirmation. It does not exist to date the archive by itself -- see
// dateProposer.ts for why a year in a summary is a much weaker claim
// than a year in a title, and why the low-confidence proposals are
// expected to be corrected rather than accepted.
//
// NOTE: Documents has no date_display/date_sort column yet. The SQL this
// emits assumes schema/migrations/003-document-dates.sql has been
// applied; that migration is written but deliberately NOT applied.

import { DatabaseSync } from 'node:sqlite'
import { writeFileSync } from 'node:fs'
import { proposeDate } from './dateProposer.ts'
import type { Confidence, DocumentForDating } from './dateProposer.ts'

const DEFAULT_DB =
  '/Users/ansonnickel/Library/Mobile Documents/com~apple~CloudDocs/frau-erica-db/frau_erica.db'

function flag(name: string): string | undefined {
  return process.argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3)
}
function has(name: string): boolean {
  return process.argv.includes(`--${name}`)
}

const db = new DatabaseSync(flag('db') ?? process.env.FRAU_ERICA_DB ?? DEFAULT_DB, {
  readOnly: true,
})

// Entry points only: the German half of a parallel text is the same work
// on the same date, and dating it separately would put the pair on a
// timeline twice.
const rows = db
  .prepare(
    `SELECT document_id, title, series_title, summary, content
       FROM Documents
      WHERE is_published = 1 AND parallel_of IS NULL
      ORDER BY document_id`,
  )
  .all() as unknown as DocumentForDating[]

interface Row {
  document_id: number
  title: string
  display: string | null
  sort: string | null
  confidence: Confidence | null
  note: string
}

const results: Row[] = rows.map((row) => {
  const { proposal, declined } = proposeDate(row)
  return {
    document_id: row.document_id,
    title: (row.title ?? '').replace(/\s+/g, ' ').trim(),
    display: proposal?.display ?? null,
    sort: proposal?.sort ?? null,
    confidence: proposal?.confidence ?? null,
    note: proposal?.source ?? declined ?? 'no year found anywhere',
  }
})

const wanted = flag('confidence')
const shown = wanted
  ? results.filter((r) => r.confidence === wanted || (wanted === 'none' && !r.confidence))
  : results

for (const r of shown) {
  const tag = (r.confidence ?? 'none').toUpperCase().padEnd(6)
  console.log(
    `${String(r.document_id).padStart(4)}  ${tag} ${(r.display ?? '--').padEnd(18)} ` +
      `${(r.sort ?? '').padEnd(11)} ${r.title.slice(0, 44)}`,
  )
  console.log(`        ${r.note}`)
}

const count = (c: Confidence | null) => results.filter((r) => r.confidence === c).length
console.log(`\n${'='.repeat(78)}`)
console.log(`${results.length} published documents`)
console.log(`  high    ${count('high')}  -- a date in the title or kicker`)
console.log(`  medium  ${count('medium')}  -- a dateline at the top of the text`)
console.log(`  low     ${count('low')}  -- a year mentioned somewhere; check each one`)
console.log(`  none    ${count(null)}  -- nothing found, or deliberately declined`)

function sqlString(v: string): string {
  return `'${v.replace(/'/g, "''")}'`
}

const out = flag('out')
if (out) {
  // High and medium only, unless asked otherwise. A low-confidence
  // proposal is a starting point for a human, not something to load in
  // bulk -- and a wrong date that looks answered never gets re-checked,
  // which is worse than an empty column.
  const includeLow = has('include-low')
  const writable = results.filter(
    (r) =>
      r.confidence === 'high' ||
      r.confidence === 'medium' ||
      (includeLow && r.confidence === 'low'),
  )

  writeFileSync(
    out,
    [
      '-- Proposed document dates.',
      '-- Generated by scripts/proposeDates.ts. Review before applying.',
      `-- ${writable.length} of ${results.length} documents${includeLow ? ' (including low confidence)' : ' (high and medium confidence only)'}.`,
      '--',
      '-- Requires schema/migrations/003-document-dates.sql.',
      `-- Back up first:  sqlite3 "$DB" ".backup '/tmp/frau_erica.pre-dates.db'"`,
      '',
      'BEGIN;',
      '',
      ...writable.map(
        (r) =>
          `-- ${r.document_id}: ${r.title.slice(0, 60)}\n` +
          `--   ${r.confidence}: ${r.note}\n` +
          `UPDATE Documents SET date_display = ${sqlString(r.display as string)}, ` +
          `date_sort = ${sqlString(r.sort as string)} WHERE document_id = ${r.document_id};\n`,
      ),
      'COMMIT;',
      '',
    ].join('\n'),
    'utf-8',
  )
  console.log(
    `\nWrote ${writable.length} UPDATE statements to ${out} -- review, then apply with sqlite3.`,
  )
} else {
  console.log('\nNothing written. Pass --out=dates.sql to emit SQL.')
}
